---@meta
---@enum AttributeAction
AttributeAction = {
    WeaponSize= 0,
	Intimidation= 1,
	ShovePower= 2,
	ResistDizzy= 3,
	ResistShove= 4,
	EncumbranceCap= 5,
	MoveSpeed= 6,
	TacBarSize= 7,
	KnockdownRecovery= 8,
	WeaponSmallBonus= 9,
	TacBarRegen= 10,
	TacBarDamage= 11,
	ReduceRecoil= 12,
	UnarmedDamage= 13,
	BluntStun= 14,
	WeaponBigPenalty= 15,
	UnarmedArmorPierce= 16,
	MeleeDamage= 17,
	ThrowDistance= 18,
	MeleeArmorPierce= 19,
	UnarmedStun= 20,
	H2HCritDamage= 21,
	SlashStun= 22,
	SprintSpeed= 23,
	BlockPower= 24,
	ResistKnockdown= 25,
	H2HSpeed= 26,
	TraumaRecovery= 27,
	KnockdownPower= 28,
	RecoilRecovery= 29,
	RangedCritDamage= 30,
	AimWalkSpeed= 31,
	ReloadSpeed= 32,
	RangedAccuracy= 33,

}